# Data Preprocessing 

- Data preprocessing is a process of preparing the raw data and making it suitable for a machine learning model. It is the first and crucial step while creating a machine learning model.



- When creating a machine learning project, it is not always a case that we come across the clean and formatted data. 



- And while doing any operation with data, it is mandatory to clean it and put in a formatted way. So for this, we use data preprocessing task.

# What is the need of Data Preprocessing?

o A real-world data generally contains noises, missing values, and maybe in an unusable format which cannot be directly used for machine learning models. 


o Data preprocessing is required tasks for cleaning the data and making it suitable for a machine learning model which also increases the accuracy and efficiency of a machine learning model.

#### It involves below steps:

    Getting the dataset
    Importing libraries
    Importing datasets
    Finding Missing Data
    Encoding Categorical Data
    Splitting dataset into training and test set
    Feature scaling


In [1]:
import numpy as np
import pandas as pd

In [2]:
#country , age and salary
data = [['India',38.0,68000.0],  
    ['France',43.0,45000.0],  
 ['Germany',30.0, 54000.0],  
 ['France' ,48.0, 65000.0], 
 ['Germany' ,40.0, np. nan],  
 ['India' ,35.0, 58000.0],  
 ['Germany', np.nan ,53000.0],  
 ['France' ,49.0, 79000.0],  
 ['India', 50.0 ,88000.0],  
 ['France' ,37.0, 77000.0]]  
    

In [3]:
df = pd.DataFrame(data,columns=['country','age','salary'])
df

,country,age,salary
0,India,38.0,68000.0
1,France,43.0,45000.0
2,Germany,30.0,54000.0
3,France,48.0,65000.0
4,Germany,40.0,NaN
5,India,35.0,58000.0
6,Germany,NaN,53000.0
7,France,49.0,79000.0
8,India,50.0,88000.0
9,France,37.0,77000.0


In [ ]:
#check null values

In [ ]:
#Assiggnment
# Plot the NaN present in your dataset

# Ways to handle missing data:

#### There are mainly two ways to handle missing data, which are:

- *By deleting the particular row:* The first way is used to commonly deal with null values. In this way, we just delete the specific row or column which consists of null values. But this way is not so efficient and removing data may lead to loss of information which will not give the accurate output.




- *By calculating the mean:* In this way, we will calculate the mean of that column or row which contains any missing value and will put it on the place of missing value. This strategy is useful for the features which have numeric data such as age, salary, year, etc. Here, we will use this approach. 

In [ ]:
#handling missing data (Replacing missing data with the mean value)  
# SimpleImputer

In [ ]:
#Fitting imputer object to the independent variables x.   
  

In [ ]:
#Replacing missing data with the calculated mean value using transform


In [ ]:
# if we want to perform fit and transform together?


# Encoding Categorical data:

- Categorical data is data which has some categories such as,  Country


- Since machine learning model completely works on mathematics and numbers, but if our dataset would have a categorical variable, then it may create trouble while building the model. So it is necessary to encode these categorical variables into numbers. 

In [ ]:
# using replace

In [ ]:
# using map


# sklearn.preprocessing

## Label Encoder: encoding technique used to convert categorical data into a numeric one
## it follows sequence order

In [4]:
df.country

0      India
1     France
2    Germany
3     France
4    Germany
5      India
6    Germany
7     France
8      India
9     France
Name: country, dtype: object

In [5]:
#import
from sklearn.preprocessing import LabelEncoder

In [6]:
lb = LabelEncoder()

In [7]:
lb.fit(df.country)

LabelEncoder()

In [8]:
lb.classes_

array(['France', 'Germany', 'India'], dtype=object)

In [9]:
#convert cat to num
lb.transform(df.country)

array([2, 0, 1, 0, 1, 2, 1, 0, 2, 0])

In [10]:
df.country

0      India
1     France
2    Germany
3     France
4    Germany
5      India
6    Germany
7     France
8      India
9     France
Name: country, dtype: object

In [ ]:
#in above case labelencoder converted India as 2, France as 0 and germany as 1

In [11]:
# lets say we have a new data to convert
# we have trained lb already
# now just use a transform method to convert
data = ['France','Germany','India','India','Germany']

In [12]:
lb.transform(data)

array([0, 1, 2, 2, 1])

In [13]:
# if u want to perform inverse operation
data_2 = [2,2,1,1,0,0]
lb.inverse_transform(data_2)

array(['India', 'India', 'Germany', 'Germany', 'France', 'France'],
      dtype=object)

In [14]:
#Apply fit() and transform() combinely
lb.fit_transform(df.country)

array([2, 0, 1, 0, 1, 2, 1, 0, 2, 0])

In [ ]:
# Interview question:
# What are different ways to deal with Categorical data?
# How to convert categorical data using pandas
# how to convert categorical data using sklearn.preprocessing

In [ ]:
from sklearn.preprocessing

# Dummy Variables:

- Dummy variables are those variables which have values 0 or 1. 


- The 1 value gives the presence of that variable in a particular column, and rest variables become 0. 


- With dummy encoding, we will have a number of columns equal to the number of categories.


- In our dataset, we have 3 categories so it will produce three columns having 0 and 1 values.

#### Wherever we have categorical data ina column, there u have to apply OneHotEncoder

In [15]:
#Encoding for dummy variables using OneHotEncoder
from sklearn.preprocessing import OneHotEncoder

In [16]:
one_hot = OneHotEncoder()

In [18]:
#fit_transform
one_hot.fit_transform(df[['country']])

<10x3 sparse matrix of type '<class 'numpy.float64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [24]:
# as the output is a sparse matrix , we need to convert into an array
conv = one_hot.fit_transform(df[['country']]).toarray()
conv

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [21]:
one_hot.categories_

[array(['France', 'Germany', 'India'], dtype=object)]

In [20]:
df.country

0      India
1     France
2    Germany
3     France
4    Germany
5      India
6    Germany
7     France
8      India
9     France
Name: country, dtype: object

In [27]:
df2 = df.copy()
df2

,country,age,salary
0,India,38.0,68000.0
1,France,43.0,45000.0
2,Germany,30.0,54000.0
3,France,48.0,65000.0
4,Germany,40.0,NaN
5,India,35.0,58000.0
6,Germany,NaN,53000.0
7,France,49.0,79000.0
8,India,50.0,88000.0
9,France,37.0,77000.0


In [37]:
# Convert conv into dframe
new_df = pd.DataFrame(conv,columns=one_hot.categories_)
new_df

,France,Germany,India
0,0.0,0.0,1.0
1,1.0,0.0,0.0
2,0.0,1.0,0.0
3,1.0,0.0,0.0
4,0.0,1.0,0.0
5,0.0,0.0,1.0
6,0.0,1.0,0.0
7,1.0,0.0,0.0
8,0.0,0.0,1.0
9,1.0,0.0,0.0


In [38]:
#now combine df2 and new_df
df3 = pd.concat([df2,new_df],axis=1)
df3[:3]

,country,age,salary,"(France,)","(Germany,)","(India,)"
0,India,38.0,68000.0,0.0,0.0,1.0
1,France,43.0,45000.0,1.0,0.0,0.0
2,Germany,30.0,54000.0,0.0,1.0,0.0


In [40]:
#lets delete country column
df3.drop(columns='country',inplace=True)

In [41]:
df3.head()

,age,salary,"(France,)","(Germany,)","(India,)"
0,38.0,68000.0,0.0,0.0,1.0
1,43.0,45000.0,1.0,0.0,0.0
2,30.0,54000.0,0.0,1.0,0.0
3,48.0,65000.0,1.0,0.0,0.0
4,40.0,NaN,0.0,1.0,0.0


In [ ]:
# age France Germany India===> predict salary
  24   0       0       1
# if age is 24 and contry is India then predict the salary

## Using pandas: get_dummies()

In [43]:
df.country

0      India
1     France
2    Germany
3     France
4    Germany
5      India
6    Germany
7     France
8      India
9     France
Name: country, dtype: object

In [44]:
#Convert categorical variable into dummy/indicator variables.
pd.get_dummies(df.country)

,France,Germany,India
0,0,0,1
1,1,0,0
2,0,1,0
3,1,0,0
4,0,1,0
5,0,0,1
6,0,1,0
7,1,0,0
8,0,0,1
9,1,0,0


In [ ]:
#How to deal with categorical data
# WHat are different encoding techniques?
# difference btween onehot and get_dummies
# onehot vs get_dummies vs LabelEncoder

# Feature Scaling

- Feature scaling is the final step of data preprocessing in machine learning. 


- It is a technique to standardize the independent variables of the dataset in a specific range. 


- In feature scaling, we put our variables in the same range and in the same scale so that no any variable dominate the other variable. 

#age = 30,40,50
#salary = 65000,56000,150000,240000

### In scaling we have 2 options
- Standardization: convert a data in range(-1 to +1) or (-3 to +3)
    * formula
     
    * StandardScaler   # x -mean(total_x)/std(total_x)
- Normalization: convert a data in range(0 to 1)
    * formula
    * MinMaxScaler  # x- min()/(max()-min())

In [45]:
age = [24,45,33,45,67]

In [47]:
#StandardScaler # x -mean(total_x)/std(total_x)
(24 - np.mean(age))/np.std(age)

-1.3005476523443407

In [50]:
(67 - np.mean(age))/np.std(age)

1.674109212060269

### StandardScaler

In [ ]:
# StandardScaler   # x -mean(total_x)/std(total_x) -3 0 +3

### MinMaxScaler

In [ ]:
# MinMaxScaler  # x- min()/(max()-min())
#range of minMax scalar is 0 to 1

### Binarizer

In [ ]:
# Binarizer