In [1]:
import numpy as np

# Check different properties of numpy array

In [4]:
a = np.random.random((4,4))
a

array([[0.92637343, 0.24050156, 0.63436264, 0.31020352],
       [0.10694942, 0.04231264, 0.65558001, 0.92588782],
       [0.92971463, 0.47791901, 0.13725243, 0.19362978],
       [0.4957108 , 0.38071146, 0.99894664, 0.87013908]])

In [5]:
# size: total elements present
a.size

16

In [6]:
# check shape
a.shape

(4, 4)

In [7]:
# a memory in bytes to each element
a.itemsize

8

In [8]:
# check data type
a.dtype

dtype('float64')

In [9]:
# check a memory
a.data

In [10]:
#check dimension
a.ndim

2

# Shape manipulation

In [12]:
a

array([[0.92637343, 0.24050156, 0.63436264, 0.31020352],
       [0.10694942, 0.04231264, 0.65558001, 0.92588782],
       [0.92971463, 0.47791901, 0.13725243, 0.19362978],
       [0.4957108 , 0.38071146, 0.99894664, 0.87013908]])

In [13]:
a.shape

(4, 4)

In [ ]:
# 16 eleements: 
# 1,16
# 2,8
# 8,2
# 4,4
# 16,1
#---- 3D
"""
1,4,4
2,2,4
4,2,2
"""


## resize():it changes shae temp.

In [15]:
a.reshape(2,8)

array([[0.92637343, 0.24050156, 0.63436264, 0.31020352, 0.10694942,
        0.04231264, 0.65558001, 0.92588782],
       [0.92971463, 0.47791901, 0.13725243, 0.19362978, 0.4957108 ,
        0.38071146, 0.99894664, 0.87013908]])

In [16]:
a.reshape(16,1)

array([[0.92637343],
       [0.24050156],
       [0.63436264],
       [0.31020352],
       [0.10694942],
       [0.04231264],
       [0.65558001],
       [0.92588782],
       [0.92971463],
       [0.47791901],
       [0.13725243],
       [0.19362978],
       [0.4957108 ],
       [0.38071146],
       [0.99894664],
       [0.87013908]])

In [18]:
#3D
a.reshape((4,2,2))

array([[[0.92637343, 0.24050156],
        [0.63436264, 0.31020352]],

       [[0.10694942, 0.04231264],
        [0.65558001, 0.92588782]],

       [[0.92971463, 0.47791901],
        [0.13725243, 0.19362978]],

       [[0.4957108 , 0.38071146],
        [0.99894664, 0.87013908]]])

In [20]:
a # a is unchanged

array([[0.92637343, 0.24050156, 0.63436264, 0.31020352],
       [0.10694942, 0.04231264, 0.65558001, 0.92588782],
       [0.92971463, 0.47791901, 0.13725243, 0.19362978],
       [0.4957108 , 0.38071146, 0.99894664, 0.87013908]])

## resize(): to do changes permanently

In [21]:
a

array([[0.92637343, 0.24050156, 0.63436264, 0.31020352],
       [0.10694942, 0.04231264, 0.65558001, 0.92588782],
       [0.92971463, 0.47791901, 0.13725243, 0.19362978],
       [0.4957108 , 0.38071146, 0.99894664, 0.87013908]])

In [22]:
a.shape

(4, 4)

In [23]:
a.resize(16)#convert into 1D

In [24]:
a

array([0.92637343, 0.24050156, 0.63436264, 0.31020352, 0.10694942,
       0.04231264, 0.65558001, 0.92588782, 0.92971463, 0.47791901,
       0.13725243, 0.19362978, 0.4957108 , 0.38071146, 0.99894664,
       0.87013908])

In [25]:
a.ndim

1

In [26]:
# lets change to 2D
a.resize((4,4))

In [27]:
a

array([[0.92637343, 0.24050156, 0.63436264, 0.31020352],
       [0.10694942, 0.04231264, 0.65558001, 0.92588782],
       [0.92971463, 0.47791901, 0.13725243, 0.19362978],
       [0.4957108 , 0.38071146, 0.99894664, 0.87013908]])

In [28]:
a.resize(4,2,2)

In [29]:
a

array([[[0.92637343, 0.24050156],
        [0.63436264, 0.31020352]],

       [[0.10694942, 0.04231264],
        [0.65558001, 0.92588782]],

       [[0.92971463, 0.47791901],
        [0.13725243, 0.19362978]],

       [[0.4957108 , 0.38071146],
        [0.99894664, 0.87013908]]])

In [30]:
a.ndim

3

In [31]:
a.shape

(4, 2, 2)

In [32]:
a.resize(16)

In [33]:
a

array([0.92637343, 0.24050156, 0.63436264, 0.31020352, 0.10694942,
       0.04231264, 0.65558001, 0.92588782, 0.92971463, 0.47791901,
       0.13725243, 0.19362978, 0.4957108 , 0.38071146, 0.99894664,
       0.87013908])

In [34]:
a.ndim

1

In [35]:
a.shape

(16,)

In [36]:
a.shape

(16,)

In [37]:
a.shape = (2,8)

In [38]:
a

array([[0.92637343, 0.24050156, 0.63436264, 0.31020352, 0.10694942,
        0.04231264, 0.65558001, 0.92588782],
       [0.92971463, 0.47791901, 0.13725243, 0.19362978, 0.4957108 ,
        0.38071146, 0.99894664, 0.87013908]])

In [39]:
a.shape

(2, 8)

## transpose: convert row to column and viceversa

In [40]:
a

array([[0.92637343, 0.24050156, 0.63436264, 0.31020352, 0.10694942,
        0.04231264, 0.65558001, 0.92588782],
       [0.92971463, 0.47791901, 0.13725243, 0.19362978, 0.4957108 ,
        0.38071146, 0.99894664, 0.87013908]])

In [41]:
a.shape

(2, 8)

In [42]:
a.transpose() #changes are temp.

array([[0.92637343, 0.92971463],
       [0.24050156, 0.47791901],
       [0.63436264, 0.13725243],
       [0.31020352, 0.19362978],
       [0.10694942, 0.4957108 ],
       [0.04231264, 0.38071146],
       [0.65558001, 0.99894664],
       [0.92588782, 0.87013908]])

In [44]:
a.T

array([[0.92637343, 0.92971463],
       [0.24050156, 0.47791901],
       [0.63436264, 0.13725243],
       [0.31020352, 0.19362978],
       [0.10694942, 0.4957108 ],
       [0.04231264, 0.38071146],
       [0.65558001, 0.99894664],
       [0.92588782, 0.87013908]])

In [45]:
np.transpose(a)

array([[0.92637343, 0.92971463],
       [0.24050156, 0.47791901],
       [0.63436264, 0.13725243],
       [0.31020352, 0.19362978],
       [0.10694942, 0.4957108 ],
       [0.04231264, 0.38071146],
       [0.65558001, 0.99894664],
       [0.92588782, 0.87013908]])

# Indexing over numpy

In [50]:
b = np.arange(1,25).reshape(6,4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [51]:
# indexing in numpy works on rows
b[0]

array([1, 2, 3, 4])

In [52]:
b[4]

array([17, 18, 19, 20])

In [54]:
#access 11
b[2]

array([ 9, 10, 11, 12])

In [56]:
b[2][2]

11

In [60]:
b[2,2]

11

In [64]:
#acess 20
b[4,3]

20

In [66]:
#access 6
b[1,1]

6

In [68]:
c = b.reshape(3,4,2)
c

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]])

In [71]:
#access 12
c[1,1,1]

12

In [73]:
#access 7
c[0,3,0]

7

In [75]:
#access18
c[2,0,1]

18

# slicing

In [77]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [78]:
#slicing works on rows first
b[:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [79]:
b[2:]#last 4 rows

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [82]:
"""
[ 9, 10, 11, 12],
[13, 14, 15, 16],
"""
b[2:4]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [85]:
"""
[ 1,  2,  3,  4]
[ 9, 10, 11, 12]
[17, 18, 19, 20]
"""
b[::2]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12],
       [17, 18, 19, 20]])

In [87]:
#access first and last row
b[::5]

array([[ 1,  2,  3,  4],
       [21, 22, 23, 24]])

In [90]:
# row 13 and 21
# Rule: If we want to skip one(n) row then step by 2(n+1)

b[3::2]

array([[13, 14, 15, 16],
       [21, 22, 23, 24]])

In [93]:
# row 21 13 5
b[::-2]

array([[21, 22, 23, 24],
       [17, 18, 19, 20],
       [13, 14, 15, 16],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [96]:
b[::-2]

array([[21, 22, 23, 24],
       [13, 14, 15, 16],
       [ 5,  6,  7,  8]])

In [ ]:
# b[row:column]
# b[row_index:column_index:step]
#b[::,::]

In [98]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [101]:
"""
10,11
14,15
"""
b[2:4,1:3]

array([[10, 11],
       [14, 15]])

In [106]:
#fetch corner elements
# 1,4,21,24
b[::5,::3]

array([[ 1,  4],
       [21, 24]])

In [107]:
b.shape

(6, 4)

In [110]:
# 19,20
# 23,24
b[4:,2:]

array([[19, 20],
       [23, 24]])

In [111]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [114]:
#access middle 2 columns
b[:,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [115]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [ ]:
"""
[[ 1,  2,  3,  4],
[ 5,  6,  7,  8],
[13, 14, 15, 16],
[21, 22, 23, 24]]
"""