In [1]:
import numpy as np

In [3]:
a = np.arange(1,25).reshape(4,6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

## Conditional based selection

In [4]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [5]:
#fetch values >10
a > 10 
#performs elementwise operation
#it give boolean output

array([[False, False, False, False, False, False],
       [False, False, False, False,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [7]:
#boolean indexing is supported
a[a > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [9]:
# more than one condition we want to test
#fetch values divisible by 5 and 7
a % 5 == 0

array([[False, False, False, False,  True, False],
       [False, False, False,  True, False, False],
       [False, False,  True, False, False, False],
       [False,  True, False, False, False, False]])

In [11]:
a % 7 == 0

array([[False, False, False, False, False, False],
       [ True, False, False, False, False, False],
       [False,  True, False, False, False, False],
       [False, False,  True, False, False, False]])

In [12]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [ ]:
#Logical: and or not
# bitwise: &(and) |(or) ~(not) ^(XOR)

In [14]:
(a % 5 == 0) | (a %7 == 0)

array([[False, False, False, False,  True, False],
       [ True, False, False,  True, False, False],
       [False,  True,  True, False, False, False],
       [False,  True,  True, False, False, False]])

In [15]:
a[(a % 5 == 0) | (a %7 == 0)]

array([ 5,  7, 10, 14, 15, 20, 21])

In [16]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [18]:
#fetch values divisible by 5 and 10
a[(a%5 ==0) & (a%10 == 0)]

array([10, 20])

In [ ]:
"""
XOR
00 0
01 1
10 1
11 0
"""

In [19]:
# We want an array 4 X 4 in whcih all values must be True
np.full((4,4),True)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [21]:
np.ones((4,4),dtype='bool')

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

### We want an array 4 X 4 in whcih all values must be False

In [22]:
np.full((4,4),False)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [23]:
np.zeros((4,4),dtype=bool)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

### We want an array 4 X 4 in whcih diagonal values must be True and non diagonal False

In [24]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.identity(4,dtype=bool)

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

### We want an array 4 X 4 in whcih diagonal values must be False and non diagonal True

In [29]:
e = np.identity(4,dtype=int)
e

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [33]:
e2 = np.invert(e)
e2

array([[-2, -1, -1, -1],
       [-1, -2, -1, -1],
       [-1, -1, -2, -1],
       [-1, -1, -1, -2]], dtype=int32)

In [34]:
e2.astype('bool')

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [35]:
e

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [37]:
~ e.astype('bool')

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

In [39]:
e

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [40]:
~ 1

-2

In [41]:
~ 0

-1

In [42]:
e

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [43]:
e.dtype

dtype('int32')

In [44]:
e.astype(float)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### np.where()

In [45]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

### convert values > 10 as 1 and values<=10 as 0

In [46]:
# no.where(condition, return x if True , else y)
np.where(a>10,1,0)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [52]:
# suqare value if its % 5 ==0
np.where(a%5==0,a**2,-a)

array([[ -1,  -2,  -3,  -4,  25,  -6],
       [ -7,  -8,  -9, 100, -11, -12],
       [-13, -14, 225, -16, -17, -18],
       [-19, 400, -21, -22, -23, -24]])

In [53]:
np.where(a%5==0,a**2,0)

array([[  0,   0,   0,   0,  25,   0],
       [  0,   0,   0, 100,   0,   0],
       [  0,   0, 225,   0,   0,   0],
       [  0, 400,   0,   0,   0,   0]], dtype=int32)

In [54]:
condition = np.array(['on','off','on','on','off'])
condition

array(['on', 'off', 'on', 'on', 'off'], dtype='<U3')

In [55]:
# Convert on as 1 and off as 0
np.where(condition=='on',1,0)

array([1, 0, 1, 1, 0])

# Splitting of array

In [56]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [57]:
#Split an array into multiple sub-arrays as views into `ary`.
np.split(a,2)

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]])]

In [58]:
np.split(a,4)

[array([[1, 2, 3, 4, 5, 6]]),
 array([[ 7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18]]),
 array([[19, 20, 21, 22, 23, 24]])]

In [60]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [59]:
#columnwise split
np.split(a,2,axis=1)

[array([[ 1,  2,  3],
        [ 7,  8,  9],
        [13, 14, 15],
        [19, 20, 21]]),
 array([[ 4,  5,  6],
        [10, 11, 12],
        [16, 17, 18],
        [22, 23, 24]])]

In [62]:
np.split(a,3,axis=1)

[array([[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20]]),
 array([[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22]]),
 array([[ 5,  6],
        [11, 12],
        [17, 18],
        [23, 24]])]

In [ ]:
# Assignmentt: np.hsplit(),np.vsplit()

## np.append()

In [63]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [64]:
#Append values to the end of an array.
np.append(a,100)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24, 100])

In [65]:
np.append(a,range(101,106))

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24, 101, 102,
       103, 104, 105])

In [69]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [71]:
# append values  in row
np.append(a,[[-1],[-2],[-3],[-4]],axis=1)

array([[ 1,  2,  3,  4,  5,  6, -1],
       [ 7,  8,  9, 10, 11, 12, -2],
       [13, 14, 15, 16, 17, 18, -3],
       [19, 20, 21, 22, 23, 24, -4]])

In [74]:
#append value in column
np.append(a,[[0,0,0,0,0,0]],axis=0)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [ 0,  0,  0,  0,  0,  0]])

## np.delet()

In [75]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [76]:
a[-1]

array([19, 20, 21, 22, 23, 24])

In [77]:
"""
Signature: np.delete(arr, obj, axis=None)
Docstring:
Return a new array with sub-arrays along an axis deleted. For a one
dimensional array, this returns those entries not returned by
"""
np.delete(a,-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23])

In [78]:
# delete last row
np.delete(a,-1,axis=0)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [79]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [80]:
np.delete(a,-1,axis=1)

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23]])

In [81]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [83]:
np.delete(a,[2,3],axis=1)

array([[ 1,  2,  5,  6],
       [ 7,  8, 11, 12],
       [13, 14, 17, 18],
       [19, 20, 23, 24]])