In [1]:
import numpy  as np

In [2]:
# create an array
a = np.arange(24).reshape(4,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [3]:
# find out values from array those are multiple of 5
a %5 == 0

array([[ True, False, False, False, False,  True],
       [False, False, False, False,  True, False],
       [False, False, False,  True, False, False],
       [False, False,  True, False, False, False]])

In [4]:
#  we can use above boolean output as an index
# Array supports boolean indexing
a[a %5 == 0]

array([ 0,  5, 10, 15, 20])

In [7]:
#  find out values from array those are multiple of 5 and 7
(a%5 == 0) ,(a%7 == 0)

(array([[ True, False, False, False, False,  True],
        [False, False, False, False,  True, False],
        [False, False, False,  True, False, False],
        [False, False,  True, False, False, False]]),
 array([[ True, False, False, False, False, False],
        [False,  True, False, False, False, False],
        [False, False,  True, False, False, False],
        [False, False, False,  True, False, False]]))

In [11]:
#combine 2 output
# logical: and, or ,not (for comparing 1-1 input use this)
#(12%5 ==0) and (20%2 ==0)
# bitwise: & | ~ ^ (for comparing many to many)

(a%5 == 0) & (a%7 == 0)


array([[ True, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [12]:
a[(a%5 == 0) & (a%7 == 0)]

array([0])

In [13]:
a[(a%5 == 0) | (a%7 == 0)]

array([ 0,  5,  7, 10, 14, 15, 20, 21])

# Create a 4x4 array whose all values set to True

In [14]:
int(True)

1

In [15]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.ones((4,4),dtype='bool')

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [18]:
np.full((4,4),fill_value=True)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

### Assignment: Create a 4x4 array whose all values set to False

## Create a 4x4 array whose diagonal values set to True and Non diagonal False

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.eye(4,dtype='bool')

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [23]:
np.identity(4,dtype='bool')

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

## Create a 4x4 array whose diagonal values set to False and Non diagonal True

In [24]:
k = np.identity(4,dtype='bool')
k

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [25]:
~ k

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

In [26]:
~np.identity(4,dtype='bool')

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

In [27]:
~ True

-2

In [32]:
~ np.identity(4,dtype=int)

array([[-2, -1, -1, -1],
       [-1, -2, -1, -1],
       [-1, -1, -2, -1],
       [-1, -1, -1, -2]], dtype=int32)

In [33]:
~ np.identity(4,dtype=bool)

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

In [34]:
b = np.array([0,False,12,-34,100])
b

array([  0,   0,  12, -34, 100])

In [35]:
# bitwise: 2's complement
~ b

array([  -1,   -1,  -13,   33, -101], dtype=int32)

In [36]:
np.array([0,False,12,-34,100],dtype=bool)

array([False, False,  True,  True,  True])

In [37]:
~ np.array([0,False,12,-34,100],dtype=bool)

array([ True,  True, False, False, False])

In [39]:
a.resize(6,4)

In [40]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Access corner elements

In [42]:
# 0, 3,20,23
a.shape

(6, 4)

In [44]:
a[::5,::3] # a[row,column]

array([[ 0,  3],
       [20, 23]])

In [ ]:
#(5,7) ([::4,::6])

In [45]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## access elements present at middle

In [48]:
"""
9, 10
13, 14
"""
# access rows
a[2:4,:]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [49]:
#access column
a[2:4,1:-1]

array([[ 9, 10],
       [13, 14]])

## Random slicing

In [51]:
a[::2]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [53]:
# reverse rows and column
a[::-1,::-1]

array([[23, 22, 21, 20],
       [19, 18, 17, 16],
       [15, 14, 13, 12],
       [11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

In [55]:
a[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [57]:
a[1::3,1::3]

array([[ 5],
       [17]])

In [68]:
a[-1::-1]

array([[20, 21, 22, 23],
       [16, 17, 18, 19],
       [12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

## make all entrie of last column 0

In [72]:
#use column index: gives 1D array output
a[:,-1]

array([ 3,  7, 11, 15, 19, 23])

In [75]:
#second option: use slicing: gives 2D output
a[:,-1:]

array([[ 3],
       [ 7],
       [11],
       [15],
       [19],
       [23]])

In [76]:
a[:,-1] = 0

In [77]:
a

array([[ 0,  1,  2,  0],
       [ 4,  5,  6,  0],
       [ 8,  9, 10,  0],
       [12, 13, 14,  0],
       [16, 17, 18,  0],
       [20, 21, 22,  0]])

In [79]:
# access middle elements and replace them in clockwise direction with 1,2,3,4
# at the place of 9, 10,13,14 we want 1,2,4,3 respective
a[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [81]:
a[2:4,1:3] = [[ 1, 2],
             [4, 3]]

In [82]:
a

array([[ 0,  1,  2,  0],
       [ 4,  5,  6,  0],
       [ 8,  1,  2,  0],
       [12,  4,  3,  0],
       [16, 17, 18,  0],
       [20, 21, 22,  0]])

In [83]:
a

array([[ 0,  1,  2,  0],
       [ 4,  5,  6,  0],
       [ 8,  1,  2,  0],
       [12,  4,  3,  0],
       [16, 17, 18,  0],
       [20, 21, 22,  0]])

In [85]:
# replace last 0 by 100
a[-1,-1]

0

In [86]:
a[-1,-1] = 100

In [87]:
a

array([[  0,   1,   2,   0],
       [  4,   5,   6,   0],
       [  8,   1,   2,   0],
       [ 12,   4,   3,   0],
       [ 16,  17,  18,   0],
       [ 20,  21,  22, 100]])

In [ ]:
# indexing is used to access single entity
# slicing is used to access more than one entity
# entity means row/column