# Numpy

In [1]:
# import numpy
import numpy

In [2]:
numpy

<module 'numpy' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

In [3]:
print(dir(numpy))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__sp

### background dat structure is array

In [5]:
a = numpy.array([100,101,102,103,104])
a

array([100, 101, 102, 103, 104])

In [6]:
a[2]

102

In [7]:
a[-1]

104

In [8]:
a[0]

100

In [9]:
a

array([100, 101, 102, 103, 104])

In [10]:
# reverse array
a[::-1]

array([104, 103, 102, 101, 100])

In [11]:
# what is typee of numpy array?
type(a)

numpy.ndarray

#### ndarray:N dimensional array

In [12]:
a

array([100, 101, 102, 103, 104])

In [14]:
b = [100, 101, 102, 103, 104]
b

[100, 101, 102, 103, 104]

### q. what difference between list and numpy array

In [16]:
#numpy performs elementwise operations
print(a)
a + 100

[100 101 102 103 104]


array([200, 201, 202, 203, 204])

In [17]:
print(b)
b + 100
# in case of list its not possible

[100, 101, 102, 103, 104]


TypeError: can only concatenate list (not "int") to list

In [18]:
# memory required
a.__sizeof__()

124

In [19]:
b.__sizeof__()

104

In [ ]:
# Assignment:
# Q. what is difference between array and numpy array
# Q. what is difference between array and list

In [20]:
import array

# Structure of numpy array

In [22]:
help(numpy.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array

In [26]:
numpy.array?

In [ ]:
numpy.array #use shift+tab to get information abt any method or attribute

# numpy.array(object,dtype)

In [27]:
import numpy as np

In [28]:
np.array(100)

array(100)

In [30]:
np.array('python7')

array('python7', dtype='<U7')

In [31]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [32]:
np.array(range(101,110))

array([101, 102, 103, 104, 105, 106, 107, 108, 109])

In [33]:
np.array(True)

array(True)

In [34]:
np.array([True,False,True])

array([ True, False,  True])

## dtype: data type

In [36]:
np.array(10).dtype

dtype('int32')

In [37]:
np.array(True).dtype

dtype('bool')

In [ ]:
#8 bit 1 byte
# 32 bit 4 bytes

In [38]:
np.array(12.55)

array(12.55)

In [39]:
np.array(12.55).dtype

dtype('float64')

In [40]:
np.array(12.55).itemsize #gives output in bytes

8

In [41]:
np.array([12,34,56,67,89]).itemsize

4

# Dimenstions of numpy array

In [42]:
a

array([100, 101, 102, 103, 104])

In [43]:
#check dim of array
a.ndim

1

In [45]:
#lets create 2D array
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [46]:
x.ndim

2

In [47]:
#check shape(rows,columns)
x.shape

(2, 2)

In [48]:
y = np.array([[1,2,10],[3,4,20],[6,7,8]])
y

array([[ 1,  2, 10],
       [ 3,  4, 20],
       [ 6,  7,  8]])

In [49]:
y.ndim

2

In [50]:
y.shape

(3, 3)

## create a 3D array

In [51]:
z = np.array([[[1,2],[3,4]],
          [[6,7],[8,9]]])
z

array([[[1, 2],
        [3, 4]],

       [[6, 7],
        [8, 9]]])

In [52]:
z.ndim

3

In [53]:
z.shape #block,row,column

(2, 2, 2)

In [ ]:
#  Summary
"""
1D: collection of objects one after another, example a
2D: Collection of 1D array example x
3D: collection of 2D array eXAMPLE: z
"""

In [55]:
a

array([100, 101, 102, 103, 104])

In [58]:
list(a)

[100, 101, 102, 103, 104]

In [56]:
x

array([[1, 2],
       [3, 4]])

In [57]:
list(x)

[array([1, 2]), array([3, 4])]

In [59]:
z

array([[[1, 2],
        [3, 4]],

       [[6, 7],
        [8, 9]]])

In [60]:
list(z)

[array([[1, 2],
        [3, 4]]),
 array([[6, 7],
        [8, 9]])]

In [61]:
z.shape

(2, 2, 2)