# Numpy array creation

In [1]:
import numpy as np

## arange()

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(10,21)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
np.arange(2,101,2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [5]:
np.arange(-1,-11,-1)

array([ -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10])

## zeros():array with all zeros

In [6]:
"""
zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.
"""
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
#3D
np.zeros((3,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [10]:
# if i want int zero then
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## ones(): all 1's in array

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
# 2D

In [ ]:
# 3D

## full(): supply own value in arrray

In [12]:
#Signature: np.full(shape, fill_value, dtype=None, order='C', *, like=None)
#Docstring:
#Return a new array of given shape and type, filled with `fill_value`.

np.full((3,3),100)

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [13]:
np.full((3,3),fill_value='NA')

array([['NA', 'NA', 'NA'],
       ['NA', 'NA', 'NA'],
       ['NA', 'NA', 'NA']], dtype='<U2')

## empty():array with garbage values

In [14]:
np.empty(5)

array([1.17321481e-311, 4.03039017e+202, 2.13562113e+289, 9.48246117e+250,
       1.81875786e+174])

In [ ]:
#2D

In [ ]:
#3D

## identity(): identity matrix
- diagonal elements 1 and non diagonal 0

In [17]:
# n: means N x N array
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## eye()

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
#np.eye(N, M=None, k=0, dtype=<class 'float'>)
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [20]:
np.eye(3,4,k = 1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## linspace(): array with linearly spaced values,
- space between 2 consecutive number will be same always

In [21]:
"""
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
"""
np.linspace(2,10)

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [22]:
np.linspace(2,10,retstep=True)

(array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
         2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
         3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
         4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
         5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
         6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
         6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
         7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
         8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
         9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ]),
 0.16326530612244897)

In [23]:
np.linspace(2,10,num=25,retstep=True)

(array([ 2.        ,  2.33333333,  2.66666667,  3.        ,  3.33333333,
         3.66666667,  4.        ,  4.33333333,  4.66666667,  5.        ,
         5.33333333,  5.66666667,  6.        ,  6.33333333,  6.66666667,
         7.        ,  7.33333333,  7.66666667,  8.        ,  8.33333333,
         8.66666667,  9.        ,  9.33333333,  9.66666667, 10.        ]),
 0.3333333333333333)

In [24]:
# dont add endpoint
np.linspace(2,10,num=25,endpoint=False,retstep=True)

(array([2.  , 2.32, 2.64, 2.96, 3.28, 3.6 , 3.92, 4.24, 4.56, 4.88, 5.2 ,
        5.52, 5.84, 6.16, 6.48, 6.8 , 7.12, 7.44, 7.76, 8.08, 8.4 , 8.72,
        9.04, 9.36, 9.68]),
 0.32)

In [26]:
# 
x = np.identity(4)
x

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
np.diagonal(x)#gives u an access to diagonal elements

array([1., 1., 1., 1.])

In [28]:
np.diagonal(x) = [1,2,3,4]

SyntaxError: cannot assign to function call (Temp/ipykernel_8616/546340649.py, line 1)

## random(): creates a random number

In [31]:
#random(size=None)

#Return random floats in the half-open interval [0.0, 1.0).
np.random.random(5)

array([0.61685507, 0.56338028, 0.48566702, 0.56377015, 0.07722063])

In [53]:
# random int values
#randint(low, high=None, size=None, dtype=int)

#Return random integers from `low` (inclusive) to `high` (exclusive).

np.random.randint(7,18,12)

array([ 9,  9,  9, 14, 17, 13, 15,  7, 16, 13, 13,  9])

In [54]:
# salary data: 20000,60000
np.random.randint(20000,60001,100)

array([52286, 30046, 42295, 51011, 33369, 43734, 47419, 49573, 34850,
       29293, 54833, 40688, 37552, 41107, 51854, 41873, 59734, 48270,
       54624, 52982, 57151, 26858, 28953, 50589, 21529, 57641, 26581,
       40004, 22865, 39845, 26820, 41839, 37236, 41744, 41678, 32111,
       49512, 28523, 40035, 53627, 35977, 26397, 42187, 28131, 34644,
       43234, 51689, 32031, 38550, 33848, 44628, 36222, 40113, 28849,
       45905, 57609, 25428, 53580, 38954, 41822, 34068, 25748, 52117,
       30428, 21106, 30150, 51821, 55019, 39274, 36622, 34545, 41122,
       31020, 53156, 33376, 46582, 55815, 26771, 30346, 33007, 33230,
       25789, 48989, 29485, 37600, 57340, 20699, 42883, 53662, 20399,
       49072, 27022, 45767, 35837, 45689, 34377, 33702, 21474, 44993,
       30839])

In [55]:
# if we have array present in memory
# & we need to create a new array with same structure
x

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [56]:
np.ones_like(x)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [57]:
np.ones_like(x,dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
#np.zeros_like()
#np.empty_like()

# Typecasting in numpy

In [58]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
np.arange(10).dtype

dtype('int32')

In [59]:
np.arange(10,dtype=float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [61]:
np.arange(10,dtype=float).dtype

dtype('float64')

In [ ]:
# 8 bit: 1 Byte
# 32 bit: 4 bytes
# 64 bit: 8 bytes

In [62]:
np.arange(10,dtype=float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [65]:
np.arange(10,dtype='float16')#in bits

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float16)

In [66]:
np.arange(10,dtype='f')

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [69]:
np.arange(10,dtype='f8') #bytes

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [71]:
np.arange(10,dtype='i8')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [74]:
#np.arange(10,dtype=float)
#np.arange(10,dtype='f')
#np.arange(10,dtype='f4')
np.arange(10,dtype=np.int8)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int8)

In [95]:
np.array([1233223423123,1342134242342342],dtype='i4')

OverflowError: Python int too large to convert to C long

In [97]:
np.array(123).dtype

dtype('int32')

## After creation of an array: if we want to typecast

In [103]:
s = np.arange(20)
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [104]:
s.dtype

dtype('int32')

## astype()

In [105]:
s.astype('int64')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19], dtype=int64)

In [106]:
s.astype(object)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19], dtype=object)

In [107]:
s.astype(np.float64)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])